In [5]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv("spam.csv", encoding="latin-1")
df = df[["v1","v2"]]
df.columns=["category", "message"]
df.head()

category                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [15]:
df.category.value_counts()

ham     4825
spam     747
Name: category, dtype: int64

In [16]:
df['spam'] = df['category'].apply(lambda x: 1 if x=="spam" else 0)

In [17]:
df.head()

category                                            message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [19]:
df.drop(columns=["category"], inplace=True)


In [20]:
df.head()

message  spam
0  Go until jurong point, crazy.. Available only ...     0
1                      Ok lar... Joking wif u oni...     0
2  Free entry in 2 a wkly comp to win FA Cup fina...     1
3  U dun say so early hor... U c already then say...     0
4  Nah I don't think he goes to usf, he lives aro...     0

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.message, df.spam, test_size=0.2)

In [22]:
X_train

1379    No. 1 Nokia Tone 4 ur mob every week! Just txt...
4012                                                  Ok.
3976    Great NEW Offer - DOUBLE Mins & DOUBLE Txt on ...
2338                            Alright, see you in a bit
2005    Can't take any major roles in community outrea...
                              ...                        
2021    I don't have anybody's number, I still haven't...
1225    sir, you will receive the account no another 1...
3460    K.. I yan jiu liao... Sat we can go 4 bugis vi...
4612                        How much you got for cleaning
2194           Hi my email address has changed now it is 
Name: message, Length: 4457, dtype: object

In [35]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)

In [36]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [37]:
X_train_cv.shape

(4457, 7715)

In [38]:
v.get_feature_names_out()[1950:2000]

array(['confidence', 'confirm', 'confirmd', 'confirmed', 'conform',
       'confused', 'confuses', 'congrats', 'congratulation',
       'congratulations', 'connect', 'connected', 'connection',
       'connections', 'cons', 'consensus', 'consent', 'conserve',
       'consider', 'considering', 'consistently', 'console', 'constant',
       'constantly', 'contact', 'contacted', 'contacts', 'contains',
       'content', 'contented', 'contention', 'contents', 'continent',
       'continue', 'continued', 'contract', 'control', 'convenience',
       'converted', 'converter', 'convey', 'conveying', 'convince',
       'convincing', 'cook', 'cooked', 'cookies', 'cooking', 'cool',
       'cooped'], dtype=object)

In [39]:
v.vocabulary_

{'no': 4774,
 'nokia': 4783,
 'tone': 6924,
 'ur': 7163,
 'mob': 4534,
 'every': 2666,
 'week': 7394,
 'just': 3880,
 'txt': 7057,
 'nok': 4782,
 'to': 6897,
 '87021': 685,
 '1st': 336,
 'free': 2975,
 'so': 6245,
 'get': 3115,
 'txtin': 7061,
 'now': 4820,
 'and': 952,
 'tell': 6717,
 'friends': 2997,
 '150p': 308,
 '16': 320,
 'reply': 5686,
 'hl': 3445,
 '4info': 521,
 'ok': 4894,
 'great': 3228,
 'new': 4741,
 'offer': 4875,
 'double': 2429,
 'mins': 4488,
 'on': 4911,
 'best': 1322,
 'orange': 4958,
 'tariffs': 6673,
 'latest': 4030,
 'camera': 1621,
 'phones': 5160,
 'call': 1599,
 'mobileupd8': 4539,
 '08000839402': 49,
 'or': 4954,
 '2stoptxt': 415,
 'cs': 2097,
 'alright': 913,
 'see': 5948,
 'you': 7660,
 'in': 3636,
 'bit': 1363,
 'can': 1625,
 'take': 6650,
 'any': 985,
 'major': 4317,
 'roles': 5783,
 'community': 1914,
 'outreach': 4997,
 'rock': 5775,
 'mel': 4427,
 'cool': 1998,
 'we': 7370,
 'shall': 6028,
 'go': 3156,
 'have': 3355,
 'tip': 6868,
 'anyway': 997,
 'are

In [40]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [41]:
np.where(X_train_np[0]!=0)

(array([ 308,  320,  336,  521,  685,  952, 2666, 2975, 2997, 3115, 3445,
        3880, 4534, 4774, 4782, 4783, 4820, 5686, 6245, 6717, 6897, 6924,
        7057, 7061, 7163, 7394], dtype=int64),)

In [42]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [44]:
X_test_cv = v.transform(X_test)

In [46]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       969
           1       0.99      0.93      0.96       146

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [47]:
emails = [
    "Hey mohan, can we get together to watch football game tomorrow?",
    "Upto 20% discount on parking, exclusive offer just for you. Don't miss this reward!"
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [48]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [49]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [51]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       969
           1       0.99      0.93      0.96       146

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.98      1115
weighted avg       0.99      0.99      0.99      1115

